sudo: false
matrix:
  include:
  - language: java
    jdk: oraclejdk8
    before_install:
      - chmod +x test/runBackend.sh
      - chmod +x test/after_success.sh
    script:
      - test/runBackend.sh
    after_success: 
      - test/after_success.sh

  - language: node_js
    node_js: 8.1.3
    before_install:
      - chmod +x test/runFrontend.sh
    before_script:
      - npm install -g @angular/cli
      - npm install
    script:
      - test/runFrontend.sh
