spring:
  application:
    name: noraui-datas-webservices
  security:
    user:
      name: admin
      password: secret
      roles: SUPERUSER
server:
  port: 8084
management:
  server:
    port: 8088
    address: localhost